//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovieDBStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovieDBStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MovieDBStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres ({0}).
        /// </summary>
        internal static string Caption_Genres {
            get {
                return ResourceManager.GetString("Caption_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachen ({0}).
        /// </summary>
        internal static string Caption_Languages {
            get {
                return ResourceManager.GetString("Caption_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopie von {0}.
        /// </summary>
        internal static string Clone_Format {
            get {
                return ResourceManager.GetString("Clone_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Große DVD Box.
        /// </summary>
        internal static string ContainerType_DVDBox {
            get {
                return ResourceManager.GetString("ContainerType_DVDBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleine DVD Box.
        /// </summary>
        internal static string ContainerType_Set {
            get {
                return ResourceManager.GetString("ContainerType_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regalfach.
        /// </summary>
        internal static string ContainerType_Shelf {
            get {
                return ResourceManager.GetString("ContainerType_Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unbekannt).
        /// </summary>
        internal static string ContainerType_Unknown {
            get {
                return ResourceManager.GetString("ContainerType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopie von {0}.
        /// </summary>
        internal static string Container_CopyFormat {
            get {
                return ResourceManager.GetString("Container_CopyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Nummer der Ergebnisseite darf nicht negativ sein..
        /// </summary>
        internal static string Exception_BadPageIndex {
            get {
                return ResourceManager.GetString("Exception_BadPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Anzahl der Ergebnisse einer Suche muss zwischen 1 und 250 liegen (jeweils einschließlich)..
        /// </summary>
        internal static string Exception_BadPageSize {
            get {
                return ResourceManager.GetString("Exception_BadPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisher ausgewählt: {0}.
        /// </summary>
        internal static string Format_Genres {
            get {
                return ResourceManager.GetString("Format_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (bei {0}).
        /// </summary>
        internal static string Format_Rent {
            get {
                return ResourceManager.GetString("Format_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltung der Aufbewahrungsbehälter und deren Standorte.
        /// </summary>
        internal static string Headline_Containers {
            get {
                return ResourceManager.GetString("Headline_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufzeichnung {0}.
        /// </summary>
        internal static string HeadLine_EditOne {
            get {
                return ResourceManager.GetString("HeadLine_EditOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuordnung zur einer Serie.
        /// </summary>
        internal static string HeadLine_Series {
            get {
                return ResourceManager.GetString("HeadLine_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen zur Serie {0}.
        /// </summary>
        internal static string HeadLine_SeriesInfo {
            get {
                return ResourceManager.GetString("HeadLine_SeriesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serieninformation pflegen.
        /// </summary>
        internal static string SeriesButton_Edit {
            get {
                return ResourceManager.GetString("SeriesButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serieninformation anlegen.
        /// </summary>
        internal static string SeriesButton_New {
            get {
                return ResourceManager.GetString("SeriesButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen zur neuen VCR.NET Mediendatenbank.
        /// </summary>
        internal static string Title_AppName {
            get {
                return ResourceManager.GetString("Title_AppName", resourceCulture);
            }
        }
    }
}
